# -*- mode: makefile -*-
# Copyright (c) 2009-2010 Satoshi Nakamoto
# Distributed under the MIT/X11 software license, see the accompanying
# file license.txt or http://opensource.org.

USE_UPNP:=0

INCLUDEPATHS= \
 -I"/opt/mingw-deps/include"

LIBPATHS= \
 -L"/opt/mingw-deps/lib"

LIBS= \
 -l boost_system \
 -l boost_filesystem \
 -l boost_program_options \
 -l boost_thread_win32 \
 -l boost_chrono \
 -l db_cxx \
 -l ssl \
 -l crypto

DEFS=-DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DSTATICLIB
DEBUGFLAGS=-g
CFLAGS=-O2 -w -Wno-invalid-offsetof -Wformat $(DEBUGFLAGS) $(DEFS) $(INCLUDEPATHS)

OBJS= \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/irc.o \
    obj/keystore.o \
    obj/main.o \
    obj/net.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcdump.o \
    obj/script.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o

ifeq ($(USE_UPNP), 1)
	INCLUDEPATHS += -I"/opt/mingw-deps/include/miniupnpc"
	LIBS += -l miniupnpc
	DEFS += -DUSE_UPNP=1
endif

LIBS += -l iphlpapi -l kernel32 -l user32 -l gdi32 -l comdlg32 -l winspool -l winmm -l shell32 -l comctl32 -l ole32 -l oleaut32 -l uuid -l rpcrt4 -l advapi32 -l ws2_32 -l shlwapi
CFLAGS += -static

CC = x86_64-w64-mingw32-gcc
CXX = x86_64-w64-mingw32-g++

all: bitcoind.exe

# Упрощенное правило компиляции (без жесткой привязки к списку HEADERS)
obj/%.o: %.cpp
	$(CXX) -c $(CFLAGS) -o $@ $<

bitcoind.exe: $(OBJS)
	$(CXX) $(CFLAGS) -o $@ $(LIBPATHS) $^ $(LIBS)

clean:
	rm -f bitcoind.exe
	rm -rf obj/*
	rm -f build.h

